version: "3.8"

services:
  app-example-ci-node:
    build: .
    container_name: app-example-ci-node
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    networks:
      - network-example-ci-node

  sonarqube-example-ci-php:
    image: sonarqube:latest
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - "9000:9000"
    networks:
      - network-example-ci-node

networks:
  network-example-ci-node:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
