  name: ci-node-workflow
  on:
    pull_request:
      branches:
        - main

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: npm install
        - name: Test and coverage
          run: npm test --coverage
        - run: cp sonar-project.properties.prod sonar-project.properties
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}
